FROM nginx:latest
COPY server-proxy.conf /etc/nginx/conf.d/default.conf
#RUN apt-get update && apt install certbot python3-certbot-nginx -y
#RUN certbot --nginx -d looks-like-a-bird.tk -d www.looks-like-a-bird.tk
