version: "3"
services:
  nginx-backend:
    container_name: nginx-backend
    #restart: unless-stopped
    image: <ACR/registry-1>
    domainname: abcdefg
    networks:
      - net-1

  nginx-proxy:
    container_name: nginx-proxy
    #restart: unless-stopped
    image: <ACR/registry-1>
    domainname: abcdefg
    ports:
      - 443:443
      - 80:80
    depends_on:
      - nginx-backend
    networks:
      - net-1
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot


  certbot:
    container_name: certbot
    #restart: unless-stopped
    image: certbot/certbot
    networks:
      - net-1
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

networks:
  net-1:
    driver: bridge
