pipelines:
  default:
      - step:
          name: Docker-compose build and push to ACR
          image: atlassian/default-image:2
          caches:
            - docker
          script:
            - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD $DOCKER_LOGIN_SERVER
            - docker-compose -f docker-compose.yml build
            - docker-compose -f docker-compose.yml push
          services:
            - docker
      - step:
          name: exec docker-compose up
          image: mcr.microsoft.com/azure-cli
          script:
            - az login --service-principal -u $AZURE_APP_ID -p $AZURE_PASSWORD --tenant $AZURE_TENANT_ID
            - az vm run-command invoke -g nginx-proxy -n myVM1 --command-id RunShellScript --scripts "sudo docker-compose -f /home/azureuser/docker-compose.yml pull  && sudo docker-compose -f /home/azureuser/docker-compose.yml up "
