pipelines:
  default:
      - step:
          name: Docker-compose build and push to ACR
          image: atlassian/default-image:2
          caches:
            - docker
          script:
             - docker login azure -u $AZURE_APP_ID -p $AZURE_PASSWORD
             - docker context create aci myacicontext --resource-group K8s-test --location eastus
          #  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD $DOCKER_LOGIN_SERVER
      #      - docker-compose -f docker-compose.yml build
      #      - docker-compose -f docker-compose.yml push
          services:
            - docker
            - docker-cli
definitions:
  services:
    docker-cli:
      image: firebelka/docker-compose-cli:latest
