version: "3"
services:
  nginx-backend:
    build: ./web-app-2/
    container_name: nginx-backend
    image: testregk8s.azurecr.io/nginx-backend
    networks:
      - net-1

  nginx-proxy:
    build: ./nginx-proxy/
    container_name: nginx-proxy
    image: testregk8s.azurecr.io/nginx-proxy
    ports:
      - 443:443
      - 80:80
    depends_on:
      - nginx-backend
    networks:
      - net-1
#    volumes:
#      - ./data/certbot/conf:/etc/letsencrypt
#      - ./data/certbot/www:/var/www/certbot


#  certbot:
#    image: certbot/certbot
#    volumes:
#      - ./data/certbot/conf:/etc/letsencrypt
#      - ./data/certbot/www:/var/www/certbot
#    depends_on:
#      - nginx-proxy


networks:
  net-1:
    driver: bridge
